### ISSUE TITLE
Sorting Request

### ISSUE THREAD

**Issue by JustForFF** [grittyfrog/MacroMate#10]
Hi Guys!

Would there be any chance of having a sort by Alphabetical/Numerical added to the plugin? Currently it doesn't auto sort by anything, just when the macro/group was added to it but I'd love a sorting feature like such.

I would like it to be able to be applied to Groups Holistically as well as the Macros inside the Groups *Seperately*. So if I sort Alphabetically while all Groups are closed, it'd sort all those Groups Alphabetically and leave my personal sorting *alone* inside the Groups. But then if I open 1, 2 or even 3 or 4 Groups and I sort Alphabetically, it'd sort all the insides of those Groups Alphabetically while leaving the Groups in their current order.

Hopefully it makes sense, and apologies if it doesn't </3

Thanks in Advance for your response!

**Comment by grittyfrog** [comment]
Yeah this seems like something that would be reasonable to add.

Do you imagine it actually sorting the list, or more of a "view" over the list which can be turned off to restore the original order? At the moment I'm thinking it would actually have to sort the group (maybe providing a Sort and Sort Recursive option to cover the two scenarios you mentioned)

**Comment by JustForFF** [comment]
Heya!!

Yes I'm looking for something that would do an actual sorting! It'd be nice to have a confirmation of sorting or maybe an undo button if I mistakenly click it, or something like where I have to hold shift and/or control to do the sorting itself baseline :D

There was another feature request I actually wanted to ask about but it's unrelated to this feature request, unsure if I should create a new one or just ask here? Sorry for making it more complicated than usual!

**Comment by grittyfrog** [comment]
Feel free to open another issue for each feature request, it helps me keep track of them :slightly_smiling_face:

**Comment by grittyfrog** [comment]
This feature is now implemented and will be available in version `1.0.11.0` (via https://github.com/grittyfrog/MacroMate/commit/75bdb4c82dad6c9b052265e7018cd5aee42ad2a0). 

The new version will be available in-game once https://github.com/goatcorp/DalamudPluginsD17/pull/3524 is reviewed and merged. :slightly_smiling_face:

**Comment by grittyfrog** [comment]
Version `1.0.11.0` is now released so I'm going to close this issue, any feedback about this feature is still more then welcome :slightly_smiling_face:
