### ISSUE TITLE
Macro Names are limited to 15 characters

### ISSUE THREAD

**Issue by JustForFF** [grittyfrog/MacroMate#11]
Hi guys!

Macros with a title more than 15 or more characters do not have their name applied in the In Game Macro Window, proof provided below:

https://github.com/grittyfrog/MacroMate/assets/85354501/cb982e30-2aa6-453a-890a-ca735956e021

Had to resize the video so quality is a bit lower but should be good enough to visualise what I found!

**Comment by grittyfrog** [comment]
Ah yep, this is a simple fix. I just hardcoded the max length to 15 instead of 20.

**Comment by JustForFF** [comment]
Thank you thank you! How soon do updates go out if you don't mind me asking?

**Comment by grittyfrog** [comment]
It depends on how quickly I get around to it, which varies a lot with my weekly schedule.

For this issue I'll likely resolve it today (after I finish with https://github.com/grittyfrog/MacroMate/issues/10). Once I push an update I then submit it to Dalamud for review which usually takes ~12 hours, once the review is complete it becomes available to download inn game.

So generally it takes however long I need to look at it (anywhere from 1 day to 2 weeks) plus 1-2 days for review.

**Comment by grittyfrog** [comment]
This bug is fixed in version `1.0.11.0` via https://github.com/grittyfrog/MacroMate/commit/4d36e555935968e1d70d016be56a76b747dcfc6f. 

It'll be available in-game once https://github.com/goatcorp/DalamudPluginsD17/pull/3524 is merged

**Comment by grittyfrog** [comment]
Version `1.0.11.0` is now released so I'm going to close this issue. Let me know if the problem re-occurs :slightly_smiling_face:
