### ISSUE TITLE
Import macros from the in-game macro list

### ISSUE THREAD

**Issue by xyzsys** [grittyfrog/MacroMate#13]
Hello. Is it possible to import macros from the in-game macro list into Macro Mate? If not, I would like to see an import function added. Thanks!

**Comment by grittyfrog** [comment]
This seems like a good idea, I'll have a look at adding it

**Comment by xyzsys** [comment]
Thank you so much! I'm waiting for the update! Have a nice day!

**Comment by grittyfrog** [comment]
I've implemented this in version `1.0.16.0` (see https://github.com/grittyfrog/MacroMate/commit/bc20c870b78583c1ffdb03452a1a6178a6b50c38). Once https://github.com/goatcorp/DalamudPluginsD17/pull/4263 is reviewed you should be able to update to version `1.0.16.0` and import macros by right clicking on them in the vanilla UI and selecting "Import to Macro Mate".

Let me know if you run into any issues, and thanks for the feature suggestion :slightly_smiling_face:

**Comment by xyzsys** [comment]
Awesome! Thanks for the ultra fast update. Looks like the review isn't done yet. I can't wait.👏🏻

Just a look and thought, it would be nice to have a menu action to import existing macros one at a time. There are 200 macros in total if the individual ones and the shared ones combined, so importing them one at a time could be a little bit annoying.

**Comment by grittyfrog** [comment]
Yeah good idea, I'll look at adding a bulk import soon :slightly_smiling_face:

**Comment by xyzsys** [comment]
Hi! It seems to be working flawlessly! After the update was released, I was so enamored with how useful it was and set it up like crazy!‪🤣‬Great job!

Conclusion:
This is exactly the plugin I have been looking for a long time! It is like a dream come true. Thank you so much for developing it. It really helped me a lot!

Here are a few feedbacks:
1. I would like an option to override the macro icon with the icon specified by the /micon command if the /micon command is used in the macro.

2. I was curious and created a new character to try it out, but I have linked macros on the main character, then log in as a sub character and Macro Mate is launched, the individual macros will be replaced by the main character's ones.

This is not necessarily bad behavior, but it is a behavior that needs attention. I think there are two ways to prevent this.

One is to provide a setting that allows users to temporarily disable links per macro, per group, or all at once.

Like the macro import menu, it would be a bit tedious to disable all links one at a time, and if the links themselves are broken, the macro would lose which slot it is linked to. There is a natural desire to temporarily break the links but retain the relationship to the slots. In addition, this has the advantage that it can be used for other purposes that require temporary unlinking, but if the user forgets to disable it and logs in as a sub character, the macro will be replaced.

Another option would be to allow the character itself to be specified as a link condition. This would have no risk of forgetting to disable it. Furthermore, this would mean that all of the 200 slots could be set up individual or shared by the users themselves!

It might be a bit of a hassle, but I think both of these options would be nice to have.

Thanks again!

**Comment by grittyfrog** [comment]
I've pushed version `1.0.17.0` which has a 'Bulk Import' feature which might be useful for this type of scenario in the future :slightly_smiling_face:.

> I would like an option to override the macro icon with the icon specified by the /micon command if the /micon command is used in the macro.

I think this is a good idea, but it's a little tricky to implement. I'll look at adding it but it might take some time.

> I was curious and created a new character to try it out, but I have linked macros on the main character, then log in as a sub character and Macro Mate is launched, the individual macros will be replaced by the main character's ones. ...

Yeah this is definitely a problem with the current macro mate setup system. There's been some talk in Dalamud about having per-character configs which would also solve this issue (though then you couldn't actually share macros).

Rather then having 'Character' be a condition I'm considering making the 'Character' (or characters) that has a macro an explicit part of the config, which would let people configure exactly which characters should have a particular macro mate macro at all. 

Maybe even having a combination of both would make sense, something like a character condition _and_ a notion of which macros belong to which character (and thus would/wouldn't show up in the Macro Mate tree at all). 

This will also probably take me some time to fix, I need to have a proper think about how this system should work.

**Comment by xyzsys** [comment]
I see. If possible, it would be nice to be able to manage macros for all characters on Macro Mate, so that a macro created for Character A can be applied to Character B as well.😁

**Comment by xyzsys** [comment]
Hi, I've tried bulk importing! I've only tried it a few times, but it appears to be working properly. Being able to specify the range to import and being able to skip macros managed by Macromate was more than I expected. Smart and thoughtful! Great job!👏🏻

**Comment by grittyfrog** [comment]
Seems that import is working well, I've captured the multi-character stuff in https://github.com/grittyfrog/MacroMate/issues/16 and will take a look at it when I have time
