### ISSUE TITLE
Custom chat commands for macros

### ISSUE THREAD

**Issue by mgrenier25** [grittyfrog/MacroMate#6]
I have no idea if this would even be possible but the ability to create custom chat commands for the macros stored in this plugin would be amazing

**Comment by grittyfrog** [comment]
I'll have a think about this, there would need to be a few restrictions (such as not being able to use this command in other macros), and I'll need to think about how to assign commands to macros/macro groups.

**Comment by grittyfrog** [comment]
Closing this issue now, happy to re-open with more feedback but at the moment I can't figure out a nice design for this without knowing how it will be used.
