### ISSUE TITLE
[Feature request] Add Player Conditions to macro conditions

### ISSUE THREAD

**Issue by Uriei** [grittyfrog/MacroMate#7]
Hi, could it be possible to add the own player condition status to the conditions for a macro to enable? So for example, to use a macro or another if I'm flying or not, or underwater, mounted, etc.

![image](https://github.com/grittyfrog/MacroMate/assets/6078221/62a0f01e-c669-4092-99cc-43aa608d856c)
![image](https://github.com/grittyfrog/MacroMate/assets/6078221/b99e52cc-6b33-4d55-b337-69f003a722b6)

**Comment by grittyfrog** [comment]
Yeah this seems useful, I'll add it in the next week or two as I don't have a lot of time to work on MacroMate this week

**Comment by grittyfrog** [comment]
This feature is now available in the `v1.0.10.0` release (see also https://github.com/grittyfrog/MacroMate/commit/dd5453a501e6f5ca6461cb6a792dc224a2a19068). Thanks again for the suggestion :slightly_smiling_face: 

It'll be available in game once https://github.com/goatcorp/DalamudPluginsD17/pull/3500 is merged.

I'm going to close this issue, but feel free to respond / reopen if you run into any issues.
